import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer1 from "../components/footer1"
import Footer2 from "../components/footer2"
import Footer3 from "../components/footer3"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Footer1/>
        <Footer2/>
        <Footer3/>
      </body>
    </html>
  );
}
